import { basename, extname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { env } from "~/server/env.ts";

// Stored URL → browser-loadable URL.
// - https://res.cloudinary.com/... passes through unchanged.
// - file:///<abs>/storage/scraps/... rewrites to /media/scraps/... (served by routes/media.ts).

export function toClientMediaUrl(rawUrl: string): string {
	if (rawUrl.startsWith("file://")) {
		return `/media/${fileUrlToStorageRelative(rawUrl)}`;
	}
	return rawUrl;
}

// Stored URL → browser-loadable thumbnail URL.
// - Cloudinary: insert a transformation segment after /image/upload/.
// - file://: point to /media/thumbnails/<id>.webp (pre-generated by the local driver).
export function toClientThumbnailUrl(rawUrl: string): string {
	if (rawUrl.startsWith("file://")) {
		const rel = fileUrlToStorageRelative(rawUrl);
		const id = basename(rel, extname(rel));
		return `/media/thumbnails/${id}.webp`;
	}
	return rawUrl.replace("/image/upload/", "/image/upload/w_600,q_80,f_webp/");
}

function fileUrlToStorageRelative(fileUrl: string): string {
	const abs = fileURLToPath(fileUrl);
	const root = resolve(env.STORAGE_ROOT);
	return relative(root, abs).split("\\").join("/");
}
